apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: deployment
  labels: 
    app: lab2-web-app
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: lab2-web-app 
  template: 
    metadata: 
      labels: 
        app: lab2-web-app
    spec: 
      containers: 
      - name: http
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports: 
        - name: custom-port
          containerPort: 3000
        env: 
        - name: REACT_APP_USERNAME 
          value: "Ilya German" 
        - name: REACT_APP_COMPANY_NAME 
          value: "ITMO" 